version: '3.3'
services:
    dynamodb:
        image: amazon/dynamodb-local:latest
        restart: always
        ports:
            - "8000:8000"
        command: [-jar, DynamoDBLocal.jar, -sharedDb, -inMemory]
    client:
        build: .
        restart: always
        depends_on: 
            - dynamodb
        ports:
            - 3000:3000
        environment:
            WAIT_HOSTS: dynamodb:8000